---
# FIX: This logic needs to be better as the hosts counts can be correct but they may not be in a ready state yet.
# This returns incorrect json that doesn't contain what is needed.
- name: "Wait for hosts to register in Assisted Installer"
  vars:
    desired_count: "{{ control_plane_count | int + compute_count | int }}"
  ansible.builtin.uri:
    url: "{{ assisted_api_url }}/clusters/{{ cluster_id }}/hosts?with-inventory=true"
    method: GET
    headers:
      Authorization: "Bearer {{ assisted_access_token }}"
      Accept: "application/json"
    status_code: [200]
    return_content: true
  register: _hosts
  retries: 120
  delay: 10
  until: (_hosts.json | length) >= desired_count
  no_log: true

- name: "Persist raw hosts list"
  ansible.builtin.copy:
    dest: "{{ artifacts_dir }}/{{ cluster_name }}/raw/hosts-initial.json"
    content: "{{ _hosts.json | to_nice_json }}"
  delegate_to: localhost

- name: "Build map of parsed inventories by host_id"
  ansible.builtin.set_fact:
    ocp_host_inventory: >-
      {{
        dict(
          _hosts.json | map(attribute='id')
          | zip(_hosts.json | map(attribute='inventory') | map('from_json'))
        )
      }}

- name: "Create mapping inventory_hostname -> assisted host id by matching provisioning MAC"
  ansible.builtin.set_fact:
    inventory_to_ocp_host_id: "{{ inventory_to_ocp_host_id | default({}) | combine({item: (matched_id)}) }}"
  vars:
    prov_mac: "{{ hostvars[item].provisioning_mac | lower }}"
    matched_id: >-
      {{
        (_hosts.json
          | selectattr('inventory','defined')
          | selectattr('inventory','string')
          | map('combine',{})
          | selectattr('id','defined')
          | selectattr('inventory','defined')
          | select(
              'search',
              prov_mac
            )
          | map(attribute='id')
          | list
          | first
        )
      }}
  loop: "{{ ansible_play_batch }}"
  when: hostvars[item].provisioning_mac is defined
  no_log: true

- name: "Fail if any host could not be matched"
  ansible.builtin.fail:
    msg: >-
      Could not match Assisted host to inventory host {{ item }} by
      provisioning MAC={{ hostvars[item].provisioning_mac }}. Check discovery
      boot and networking.
  loop: "{{ ansible_play_batch }}"
  when: inventory_to_ocp_host_id[item] is not defined
