---
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    platform_profile: enterprise
    platform_deployment_mode: gitops
    platform_openshift_version: "4.18"
    platform_features:
      assisted_installer: true
      redfish: true
      gitops: true
      acm: true
      acs: false
      odf: true
      openshift_virtualization: false
      metallb: true
      cert_manager: true
