apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-environments
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - environment: lab
          - environment: development
          - environment: testing
          - environment: production
  template:
    metadata:
      name: 'platform-{{environment}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/psehgaft/ocp-ansible-agent-installer.git
        targetRevision: main
        path: 'gitops/overlays/{{environment}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
