- name: "OpenShift bare-metal install via Assisted Installer and Dell iDRAC (fully automated)"
  hosts: all
  gather_facts: false
  connection: local
  vars:
    validate_certs: false
  tasks:
  - name: "Obtain Assisted Installer API access token (SaaS) from offline token"
    when: assisted_auth_mode == 'saas'
    ansible.builtin.uri:
      url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: refresh_token
        client_id: cloud-services
        refresh_token: "{{ assisted_offline_token }}"
      return_content: true
      status_code: [200]
    register: _token
    no_log: true
    run_once: true
  - name: "Set assisted_access_token fact"
    ansible.builtin.set_fact:
      assisted_access_token: >-
        {{
          (_token.json.access_token if assisted_auth_mode == 'saas' else assisted_access_token)
        }}
    no_log: true

  - name: "Fail if token is missing"
    ansible.builtin.fail:
      msg: "assisted_access_token is missing. Provide assisted_offline_token (saas) or assisted_access_token (onprem)."
    when: assisted_access_token is not defined or assisted_access_token | length == 0

  - name: "Create cluster definition"
    ansible.builtin.uri:
      url: "{{ assisted_api_url }}/clusters/dedb899c-215a-4d74-9b67-ec6df5968d23"
      method: GET
      headers:
        Authorization: "Bearer {{ assisted_access_token }}"
        Content-Type: "application/json"
        Accept: "application/json"
      return_content: true
    register: _cluster
    run_once: true
    delegate_to: localhost
    
  - name: testing
    debug:
      var: _cluster
    run_once: true