---
# Static network parameters for this host (not discoverable from iDRAC)
node_role: master
node_hostname: master-0

# Single-NIC example (use bond/bridge in nmstate if needed)
node_ipv4_address: "192.168.10.20"
node_ipv4_prefix: 24
node_ipv4_gateway: "192.168.10.1"
node_dns_servers:
  - "192.168.10.53"

# Optional: choose the installation disk by hint (if omitted, playbook auto-selects largest disk)
# install_disk_hint: "NVMe"   # e.g., match Model or Name

rhoso_worker_node_ips:
  worker0:
    br-ex: "192.168.18.241"
    External: "192.168.9.15"
    InternalAPI: "192.168.2.11"
    Storage: "192.168.4.11"
    Tenant: "192.168.6.11"
    StorageMgmt: "192.168.8.11"

    storage_1_1: "192.158.162.51"
    storage_1_2: "192.158.164.51"
    storage_2_2: "192.158.172.51"
    storage_2_1: "192.158.174.51"
    storage_3_2: "192.158.184.51"
    storage_3_1: "192.158.182.51"

    br_nfs_1: "192.158.160.51"
    br_nfs_2: "192.158.170.51"
    br_nfs_3: "192.158.180.51"
