---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: openstack-network-config
spec:
  desiredState:
    interfaces:
      - name: br-ctlplane
        description: Control plane bridge
        type: linux-bridge
        state: up
        ipv4:
          enabled: true
          dhcp: false
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: eth1
      
      - name: br-tenant
        description: Tenant network bridge
        type: linux-bridge
        state: up
        ipv4:
          enabled: false
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: eth2
