---
- name: Install and configure Red Hat Advanced Cluster Security
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components:
      - acs
    platform_operator_resources: "{{ acs_resources | default([]) }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/platform-operators/acs"
