---
- name: Configure Chrony and NTP
  hosts: localhost
  gather_facts: false
  roles:
    - role: day2_cluster_operations
      vars: {day2_cluster_domain: chrony, day2_cluster_resources: "{{ chrony_resources | default([]) }}"}
