---
- name: Install and configure the File Integrity Operator
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components: []
    platform_operator_resources: "{{ file_integrity_resources }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/security/file-integrity"
