---
- name: Configure cluster monitoring
  hosts: localhost
  gather_facts: false
  roles:
    - role: day2_operational_workflow
      vars: {day2_operation_domain: monitoring, day2_operation_resources: "{{ monitoring_resources | default([]) }}"}
