---
- name: Install and configure Migration Toolkit for Virtualization
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components:
      - mtv
    platform_operator_resources: "{{ mtv_resources | default([]) }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/platform-operators/mtv"
