---
- name: Configure platform PKI resources
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components: []
    platform_operator_resources: "{{ pki_resources }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/platform-operators/pki"
