---
- name: Install and configure Network Observability Operator
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components: []
    platform_operator_resources: "{{ network_observability_resources }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/platform-operators/network-observability"
