---
- name: Install and configure Local Storage Operator
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components: []
    platform_operator_resources: "{{ local_storage_resources }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/platform-operators/storage/local-storage"
