---
- name: Install and configure OpenShift Data Foundation
  ansible.builtin.import_playbook: platform-operator-bundle.yml
  vars:
    platform_operator_components:
      - odf
    platform_operator_resources: "{{ storage_operator_resources | default([]) }}"
    platform_operator_render_root: "{{ playbook_dir }}/../../rendered/day2/platform-operators/storage/odf"
