all:
  children:
    idrac:
      hosts:
        master-0:
          idrac_ip: 192.0.2.10
        master-1:
          idrac_ip: 192.0.2.11
        master-2:
          idrac_ip: 192.0.2.12
        worker-0:
          idrac_ip: 192.0.2.20
        worker-1:
          idrac_ip: 192.0.2.21

  vars:
    