- name: "Do full discovery when files don't exist"
  ansible.builtin.include_role:
    name: idrac_discovery_full
  when: not lookup('file', "{{ artifacts_dir }}/{{ cluster_name }}/raw/idrac-{{ inventory_hostname }}.json", errors='ignore')

- name: "Read iDRAC discovery data from file"
  ansible.builtin.set_fact:
    idrac_data: "{{ lookup('file', '{{ artifacts_dir }}/{{ cluster_name }}/raw/idrac-{{ inventory_hostname }}.json') | from_json }}"

- name: "Set required facts"
  ansible.builtin.set_fact:
    idrac_nics: "{{ idrac_data.nics }}"
    idrac_disks: "{{ idrac_data.disks }}"
    provisioning_mac: "{{ idrac_data.provisioning_mac }}"
    idrac_ip: "{{ idrac_data.idrac_ip }}"

- name: "Flatten NIC data structure to get actual NIC objects"
  ansible.builtin.set_fact:
    flat_nics: "{{ idrac_nics[0][1] if (idrac_nics | length > 0 and idrac_nics[0] | length > 1) else [] }}"

